### ISSUE TITLE
加载报错[BUG] 

### ISSUE THREAD

**Issue by dabai123456** [gh0stkey/CaA#21]
## 使用环境

```
CaA版本：0.9
BurpSuite版本：22.3.7
JDK版本：BurpSuite自带
操作系统版本：windows11
```

## 问题详情

问题描述：
安装插件时报错
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at burp.cvr.a(Unknown Source)
	at burp.cvr.<init>(Unknown Source)
	at burp.cru.a(Unknown Source)
	at burp.av0.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
CaA只支持2024年版本的BurpSuite
